### ISSUE TITLE
Collect traffic metrics for RiskProfiler and associated downloads and GitHub Pages

### ISSUE THREAD

**Issue by anthonyfok** [OpenDRR/opendrr#140]
There is a real need to monitor or collect related statistics of traffic to [www.riskprofiler.ca](https://www.riskprofiler.ca/)  and associated downloads to track usage, popularity and performance, etc. of our beloved project.

## TODOs

- [ ] Check Amazon CloudFront usage for RiskProfiler web pages
- [ ] GitHub release assets download stats
- [ ] GitHub repo access stats
- [ ] Possibility of adding Google Analytics to GitHub Pages as GitHub does not provide server-side stats on them.
- [ ] Check Amazon CloudFront usage for vector map tiles.
- [ ] Collect the above data daily and provide charts and tables for easy viewing and tracking over time.

## Background Information

Malaika (@malaikau) thoughtfully asked:

> Do you know if we can monitor traffic or downloads from riskprofiler.ca?

To which I replied:

> Great question!  This is a topic that Joost brought over a year ago, quite some time before the RiskProfiler launch, for GitHub Pages and for the downloads of GitHub release assets (e.g. GeoPackage files.)

> Google Analytics was briefly considered and tried out, though there were privacy concerns that we probably stopped using it altogether.  (My memory is a bit vague in this area; I'll go check.)

> As for downloads, GitHub has an API that allows us to query how many times a file (release asset) was downloaded.  We tested that it does work, but I failed to follow up to do a regular API poll to keep track of that statistics.  I think this would be a fun side project this year.  (should be relatively simple and won't take too much time)

> As for access to the web pages on [RiskProfiler.ca](http://riskprofiler.ca/), no Google Analytics is in place, though Arash set RiskProfiler up to be served from Amazon CloudFront (caching, content delivery network) which apparently has some sort of traffic monitoring built in: https://aws.amazon.com/cloudfront/reporting/

> I'll go explore to see if that's indeed the case and share some charts with you if available.

> And thank you so much for bringing this up!  (This is something that I should have recalled to do and yet escaped my mind completely. My bad!)  I'll start exploring an automated collection of all relevant site visits and downloads statistics/metrics on a regular basis (daily, monthly, etc.) and have them available in one place for easy viewing.

And Malaika kindly replied:

> Thank you! That would be great. And no hurry, but it will help us consider what and how we measure things...
